baseURL = "https://musikum.netlify.com"
languageCode = "de-de"
summaryLength = "10"
theme = "kross-hugo"
title = "musikum e.V."
[[menu.main]]
URL = "kontakt"
name = "Kontakt"
weight = ""
[[menu.main]]
URL = "kooperationspartner"
name = "Kooperationspartner"
weight = ""
[[menu.main]]
URL = "räume-mieten"
name = "Räume mieten"
weight = ""
[[menu.main]]
URL = "Unterstuetzen"
name = "Unterstützen"
weight = ""
[[menu.main]]
URL = "preise"
name = "Preise"
weight = ""
[[menu.main]]
URL = "termine"
name = "Termine"
weight = ""
[[menu.main]]
URL = "ueber-uns"
name = "Über uns"
weight = "3"
[[menu.main]]
URL = "angebote"
name = "Angebote"
weight = "2"
[params]
address = "Mengstr. 40 B, 23552 Lübeck"
author = "Nicolai Schmid"
copyright = "Copyrighht &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"
description = "Das musikum e.V. in Lübeck"
email = "info@musikum-luebeck.de"
google_analitycs_id = "Your ID"
home = "Startseite"
logo = "images/logo.png"
phone = "0451 - 70 43 86"
social = []
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
